"""Utilities module for FastAPI Auth Service."""

from .status_codes import *
from .http_messages import *

__all__ = [
    # Status codes
    "HTTP_OK", "HTTP_CREATED", "HTTP_BAD_REQUEST", "HTTP_UNAUTHORIZED", 
    "HTTP_NOT_FOUND", "HTTP_CONFLICT", "HTTP_INTERNAL_SERVER_ERROR",
    
    # HTTP messages
    "HTTP_OK_MESSAGE", "HTTP_CREATED_MESSAGE", "HTTP_BAD_REQUEST_MESSAGE",
    "HTTP_UNAUTHORIZED_MESSAGE", "HTTP_NOT_FOUND_MESSAGE", "HTTP_CONFLICT_MESSAGE",
    "HTTP_INTERNAL_SERVER_ERROR_MESSAGE", "HTTP_TOKEN_REQUIRED_MESSAGE",
    "HTTP_TOKEN_EXPIRED_MESSAGE", "HTTP_INVALID_SIGNATURE_MESSAGE",
    "HTTP_INVALID_TOKEN_MESSAGE", "HTTP_REGISTER_BAD_REQUEST_MESSAGE",
    "HTTP_REGISTER_USER_EXISTS_MESSAGE", "HTTP_REGISTER_CREATED_MESSAGE",
    "HTTP_LOGIN_SUCCESS_MESSAGE", "HTTP_LOGIN_BAD_REQUEST_MESSAGE",
    "HTTP_LOGIN_INVALID_CREDENTIALS_MESSAGE", "HTTP_GET_USER_SUCCESS_MESSAGE",
    "HTTP_GET_USER_BY_EMAIL_UNAUTHORIZED_MESSAGE", "HTTP_GET_USER_BY_ID_UNAUTHORIZED_MESSAGE",
    "HTTP_USER_NOT_FOUND_MESSAGE", "HTTP_PASSWORD_UPDATE_SUCCESS_MESSAGE",
    "HTTP_PASSWORD_UPDATE_BAD_REQUEST_MESSAGE", "HTTP_DELETE_USER_SUCCESS_MESSAGE",
    "HTTP_DELETE_USER_UNAUTHORIZED_MESSAGE", "HTTP_DELETE_USER_SUPER_ADMIN_MESSAGE",
    "HTTP_DELETE_USER_SELF_MESSAGE", "HTTP_GET_PATIENTS_UNAUTHORIZED_MESSAGE",
    "HTTP_GET_PATIENTS_SUCCESS_MESSAGE"
]